# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='target_params',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target_target',
            field=models.CharField(default=1, help_text='Link target', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target_type',
            field=models.SmallIntegerField(choices=[(0, 'URL'), (1, 'Named URL'), (2, 'Page'), (3, 'Blog Post')], default=1),
            preserve_default=False,
        ),
    ]
