# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_confirm', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('django_confirm.confirmation',),
        ),
    ]
