# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('core', '0002_auto_20160602_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('jid', models.CharField(max_length=255, unique=True, verbose_name='JID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gpg_fingerprint', models.CharField(blank=True, max_length=40, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('registration_method', models.SmallIntegerField(choices=[(0, 'Via Website'), (1, 'In-Band Registration'), (2, 'Manually'), (9, 'Unknown')])),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
        ),
    ]
