# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_confirmation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
            ],
        ),
    ]
