# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_cachedmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'IP-Address',
                'verbose_name_plural': 'IP-Addresses',
            },
        ),
        migrations.CreateModel(
            name='AddressActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.SmallIntegerField(choices=[(0, 'Registration'), (1, 'Reset password'), (2, 'Set password'), (3, 'Set email')])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP-Address Activity',
                'verbose_name_plural': 'IP-Address Activities',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='activities',
            field=models.ManyToManyField(through='core.AddressActivity', to=settings.AUTH_USER_MODEL),
        ),
    ]
