# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160903_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title_de',
            field=models.CharField(help_text='Page title', max_length=32),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(help_text='Page title', max_length=32),
        ),
    ]
