# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:55
from __future__ import unicode_literals

import core.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160608_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='target_params',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='target_target',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='target_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target',
            field=core.modelfields.LinkTarget(default={}),
            preserve_default=False,
        ),
    ]
