# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160903_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressactivity',
            name='activity',
            field=models.SmallIntegerField(choices=[(0, 'Registration'), (1, 'Reset password'), (2, 'Set password'), (3, 'Set email'), (4, 'Failed login')]),
        ),
    ]
