# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160924_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='html_summary_de',
            field=models.TextField(blank=True, help_text='Any length, but must be valid HTML. Shown in RSS feeds.', null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='html_summary_en',
            field=models.TextField(blank=True, help_text='Any length, but must be valid HTML. Shown in RSS feeds.', null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_summary_de',
            field=models.CharField(blank=True, help_text='For search engines, max. of 160 characters.', max_length=160, null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_summary_en',
            field=models.CharField(blank=True, help_text='For search engines, max. of 160 characters.', max_length=160, null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='opengraph_summary_de',
            field=models.CharField(blank=True, help_text='Two to four sentences, default: first three sentences.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='opengraph_summary_en',
            field=models.CharField(blank=True, help_text='Two to four sentences, default: first three sentences.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_summary_de',
            field=models.CharField(blank=True, help_text='At most 200 characters.', max_length=200, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_summary_en',
            field=models.CharField(blank=True, help_text='At most 200 characters.', max_length=200, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_summary_de',
            field=models.TextField(blank=True, help_text='Any length, but must be valid HTML. Shown in RSS feeds.', null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_summary_en',
            field=models.TextField(blank=True, help_text='Any length, but must be valid HTML. Shown in RSS feeds.', null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_summary_de',
            field=models.CharField(blank=True, help_text='For search engines, max. of 160 characters.', max_length=160, null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_summary_en',
            field=models.CharField(blank=True, help_text='For search engines, max. of 160 characters.', max_length=160, null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='page',
            name='opengraph_summary_de',
            field=models.CharField(blank=True, help_text='Two to four sentences, default: first three sentences.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='page',
            name='opengraph_summary_en',
            field=models.CharField(blank=True, help_text='Two to four sentences, default: first three sentences.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='page',
            name='twitter_summary_de',
            field=models.CharField(blank=True, help_text='At most 200 characters.', max_length=200, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='page',
            name='twitter_summary_en',
            field=models.CharField(blank=True, help_text='At most 200 characters.', max_length=200, null=True, verbose_name='Twitter'),
        ),
    ]
