# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cachedmessage_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='html_summary_de',
            field=models.TextField(blank=True, default='', help_text='Any length, but must be valid HTML. Shown in RSS feeds.', verbose_name='HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='html_summary_en',
            field=models.TextField(blank=True, default='', help_text='Any length, but must be valid HTML. Shown in RSS feeds.', verbose_name='HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_summary_de',
            field=models.CharField(blank=True, default='', help_text='For search engines, max. of 160 characters.', max_length=160, verbose_name='Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_summary_en',
            field=models.CharField(blank=True, default='', help_text='For search engines, max. of 160 characters.', max_length=160, verbose_name='Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='opengraph_summary_de',
            field=models.CharField(blank=True, default='', help_text='Two to four sentences, default: first three sentences.', max_length=255, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='opengraph_summary_en',
            field=models.CharField(blank=True, default='', help_text='Two to four sentences, default: first three sentences.', max_length=255, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_summary_de',
            field=models.CharField(blank=True, default='', help_text='At most 200 characters.', max_length=200, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitter_summary_en',
            field=models.CharField(blank=True, default='', help_text='At most 200 characters.', max_length=200, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='html_summary_de',
            field=models.TextField(blank=True, default='', help_text='Any length, but must be valid HTML. Shown in RSS feeds.', verbose_name='HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='html_summary_en',
            field=models.TextField(blank=True, default='', help_text='Any length, but must be valid HTML. Shown in RSS feeds.', verbose_name='HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_summary_de',
            field=models.CharField(blank=True, default='', help_text='For search engines, max. of 160 characters.', max_length=160, verbose_name='Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_summary_en',
            field=models.CharField(blank=True, default='', help_text='For search engines, max. of 160 characters.', max_length=160, verbose_name='Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='opengraph_summary_de',
            field=models.CharField(blank=True, default='', help_text='Two to four sentences, default: first three sentences.', max_length=255, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='opengraph_summary_en',
            field=models.CharField(blank=True, default='', help_text='Two to four sentences, default: first three sentences.', max_length=255, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='twitter_summary_de',
            field=models.CharField(blank=True, default='', help_text='At most 200 characters.', max_length=200, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='twitter_summary_en',
            field=models.CharField(blank=True, default='', help_text='At most 200 characters.', max_length=200, verbose_name='Twitter'),
            preserve_default=False,
        ),
    ]
