# Generated by Django 2.1.5 on 2019-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171009_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressactivity',
            name='headers',
            field=models.TextField(help_text='Request headers used.'),
        ),
        migrations.AlterField(
            model_name='cachedmessage',
            name='payload',
            field=models.TextField(default='{}'),
        ),
    ]
