# Generated by Django 3.0.4 on 2020-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190120_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
