# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jid',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_method',
            field=models.SmallIntegerField(choices=[(0, 'Via Website'), (1, 'In-Band Registration'), (2, 'Manually'), (9, 'Unknown')], default=0),
        ),
    ]
