# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_in_backend',
            field=models.BooleanField(default=False),
        ),
    ]
