# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160903_1321'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='core.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_in_backend',
            field=models.BooleanField(default=False),
        ),
    ]
