# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpgkey',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlogentry',
            name='address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gpgkey',
            unique_together=set([('user', 'fingerprint')]),
        ),
    ]
