# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160906_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gpg_fingerprint',
        ),
    ]
