# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_confirmation'),
        ('django_confirm', '0001_initial'),
        ('account', '0003_auto_20160617_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('confirmation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_confirm.Confirmation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.confirmation',),
        ),
    ]
