# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notifications', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_expires', models.BooleanField(default=False, help_text='Accounts are deleted if they are not used for a year. Warn me a week before mine would be deleted.')),
                ('gpg_expires', models.BooleanField(default=False, help_text='Warn me a week before any of my GPG keys is about to expire.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
