# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:08
from __future__ import unicode_literals

from django.db import migrations


def create_notifications(apps, schema_editor):
    User = apps.get_model('account', 'User')
    Notifications = apps.get_model('account', 'Notifications')
    for u in User.objects.filter(notifications__isnull=True):
        Notifications.objects.create(user=u)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_notifications'),
    ]

    operations = [
        migrations.RunPython(create_notifications),
    ]
