# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160821_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpgkey',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
