# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20161014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='account_expires',
            field=models.BooleanField(default=True, help_text='Send user an email when the account is about to be deleted.'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='gpg_expires',
            field=models.BooleanField(default=True, help_text='Send user an email when his GPG key is about to expire.'),
        ),
    ]
