# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 08:17
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160821_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=account.models.default_key, max_length=40)),
                ('expires', models.DateTimeField(default=account.models.default_expires)),
                ('purpose', models.CharField(blank=True, max_length=16, null=True)),
                ('payload', jsonfield.fields.JSONField(default=account.models.default_payload)),
                ('language', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userconfirmation',
            name='confirmation_ptr',
        ),
        migrations.RemoveField(
            model_name='userconfirmation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
