# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160826_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='to',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Recipient'),
        ),
    ]
