# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20161226_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='purpose',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='to',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogentry',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
