# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20161226_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
