# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normalized_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
