# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20171011_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='normalized_email',
            field=models.EmailField(max_length=254),
        ),
    ]
