# Generated by Django 2.0.5 on 2018-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20171011_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpgkey',
            name='fingerprint',
            field=models.CharField(help_text='The full Fingerprint, without the "0x" prefix.', max_length=40),
        ),
    ]
