# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:21
from __future__ import unicode_literals

import antispam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.EmailField(help_text='The blocked email address', max_length=254, unique=True)),
                ('expires', models.DateTimeField(default=antispam.models._default_email_expires, help_text='When this block expires. If not set, it never expires.')),
            ],
            options={
                'verbose_name_plural': 'Blocked email addresses',
                'verbose_name': 'Blocked email address',
            },
            bases=(antispam.models.BlockedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlockedIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField(help_text='The blocked IP address', unique=True)),
                ('expires', models.DateTimeField(default=antispam.models._default_ipaddress_expires, help_text='When this block expires. If not set, it never expires.')),
            ],
            options={
                'verbose_name_plural': 'Blocked IP addresses',
                'verbose_name': 'Blocked IP address',
            },
            bases=(antispam.models.BlockedMixin, models.Model),
        ),
    ]
