# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:49
from __future__ import unicode_literals

import antispam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antispam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedemail',
            name='expires',
            field=models.DateTimeField(blank=True, default=antispam.models._default_email_expires, help_text='When this block expires. If not set, it never expires.', null=True),
        ),
        migrations.AlterField(
            model_name='blockedipaddress',
            name='expires',
            field=models.DateTimeField(blank=True, default=antispam.models._default_ipaddress_expires, help_text='When this block expires. If not set, it never expires.', null=True),
        ),
    ]
