# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metric', models.CharField(db_index=True, max_length=16)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
