# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='metric',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
