# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170221_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metric_new',
            field=models.SmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
