# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:04
from __future__ import unicode_literals

from django.db import migrations

from stats.constants import STAT_REGISTER
from stats.constants import STAT_REGISTER_CONFIRMED
from stats.constants import STAT_RESET_PASSWORD
#from stats.constants import STAT_RESET_PASSWORD_CONFIRMED
#from stats.constants import STAT_SET_PASSWORD
from stats.constants import STAT_SET_EMAIL
#from stats.constants import STAT_SET_EMAIL_CONFIRMED
from stats.constants import STAT_DELETE_ACCOUNT
#from stats.constants import STAT_DELETE_ACCOUNT_CONFIRMED
#from stats.constants import STAT_FAILED_LOGIN


def migrate_stats(apps, schema_editor):
    Event = apps.get_model('stats', 'Event')
    for e in Event.objects.all():
        if e.metric == 'password_reset':
            e.metric_new = STAT_RESET_PASSWORD
        elif e.metric == 'set_email':
            e.metric_new = STAT_SET_EMAIL
        elif e.metric == 'delete_account':
            e.metric_new = STAT_DELETE_ACCOUNT
        elif e.metric == 'register':
            e.metric_new = STAT_REGISTER
        elif e.metric == 'register_confirmed':
            e.metric_new = STAT_REGISTER_CONFIRMED
        else:
            raise Exception("Unknown metric: %s" % e.metric)
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_event_metric_new'),
    ]

    operations = [
        migrations.RunPython(migrate_stats),
    ]
