# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_event_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='metric_new',
            new_name='metric',
        ),
    ]
