# Generated by Django 2.0 on 2018-01-01 11:52

import certs.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(help_text='Primary hostname of this certificate.', max_length=255)),
                ('pem', models.TextField(help_text='Certificate, in PEM format.')),
                ('hostnames', jsonfield.fields.JSONField(blank=True, default=certs.models._default_hostnames)),
                ('key_size', models.PositiveSmallIntegerField(blank=True)),
                ('valid_from', models.DateTimeField(blank=True)),
                ('valid_until', models.DateTimeField(blank=True)),
                ('serial', models.CharField(blank=True, max_length=64)),
                ('sha1', models.CharField(blank=True, max_length=59)),
                ('sha256', models.CharField(blank=True, max_length=95)),
                ('sha512', models.CharField(blank=True, max_length=191)),
                ('tlsa', models.CharField(blank=True, max_length=191)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
