# Generated by Django 2.0 on 2018-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='sha1',
            field=models.CharField(blank=True, max_length=59, verbose_name='SHA-1'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sha256',
            field=models.CharField(blank=True, max_length=95, verbose_name='SHA-256'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sha512',
            field=models.CharField(blank=True, max_length=191, verbose_name='SHA-512'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tlsa',
            field=models.CharField(blank=True, max_length=191, verbose_name='TLSA fingerprint'),
        ),
    ]
