# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title_de', models.CharField(help_text='Page title', max_length=16)),
                ('title_en', models.CharField(help_text='Page title', max_length=16)),
                ('text_de', models.TextField()),
                ('text_en', models.TextField()),
                ('published', models.BooleanField(default=True, help_text='Wether or not the page is public.')),
                ('sticky', models.BooleanField(default=False, help_text='Pinned at the top of any list of blog posts.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
