# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True, help_text='If the article is publicly visible.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sticky',
            field=models.BooleanField(default=False, help_text='Pinned at the top of any list of blog posts.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(help_text='Title of the blog post.', max_length=16),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(help_text='Title of the blog post.', max_length=16),
        ),
    ]
