# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_de',
            field=models.CharField(default='', help_text='Slug (used in URLs)', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.CharField(default='', help_text='Slug (used in URLs)', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
