# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160602_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True, help_text='Wether or not the page is public.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(help_text='Page title', max_length=16),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(help_text='Page title', max_length=16),
        ),
    ]
