# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='end',
            field=models.DateTimeField(blank=True, help_text='When the event stops, defaults to an hour after start.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='start',
            field=models.DateTimeField(blank=True, help_text='When the event starts.', null=True),
        ),
    ]
