# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161223_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(help_text='When the article is published.', null=True),
        ),
    ]
