# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 10:17
from __future__ import unicode_literals

from django.db import migrations


def set_publication_date(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.filter(publication_date__isnull=True):
        post.publication_date = post.created
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_publication_date'),
    ]

    operations = [
        migrations.RunPython(set_publication_date),
    ]
