# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161224_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the article was published. You can also set this to a future date, if you want to publish this post in the future.'),
        ),
    ]
